on: push
jobs:
  ci:
    strategy:
      matrix:
        go_version: ['1.11', '1.12', '1.13']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
    - name: Build project
      run: |
        go build ./...
  release:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Generate release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release@next
